import {
  earsManBig,
  earsManBiten,
  earsManRingEarring,
  earsManSmall,
  earsManStandard,
  earsManStudEarrings,
  eyesManBig,
  eyesManEyelashes,
  eyesManEyelids,
  eyesManHappy,
  eyesManSmall,
  eyesManStandard,
  faceDetailsChinDimple1,
  faceDetailsChinDimple2,
  faceDetailsChinDimple3,
  faceDetailsChinDimple4,
  glassesManBrow,
  glassesManPatch,
  glassesManRound,
  glassesManSquare,
  glassesManStylish,
  hairBeanie,
  hairManBald,
  hairManCurly,
  hairManElvis,
  hairManMediumTopknot,
  hairManMessy,
  hairManShortTopknot,
  hairManStylish,
  headManBeardMustache,
  headManBeardSharp,
  headManBeardSlim,
  headManBeardStandard,
  headManBristle,
  headManBristleMustache,
  headManChin,
  headManSharp,
  headManStandard,
  mouthChin,
  mouthPhiltrum1,
  mouthPhiltrum2,
  mouthSad,
  mouthSmall,
  mouthSmile,
  mouthTongue1,
  mouthTongue2,
  mouthVampire,
  noseManBig,
  noseManBigWide,
  noseManSmall,
  noseManStandard,
  noseManWide,
} from '@avatune/pawel-olek-assets'
import type { VanillaAvatarItem } from '@avatune/types'
import shared from './shared'

export default shared
  .toFramework<VanillaAvatarItem>()
  .withComponents('ears', {
    big: { code: earsManBig },
    biten: { code: earsManBiten },
    ringEarring: { code: earsManRingEarring },
    small: { code: earsManSmall },
    standard: { code: earsManStandard },
    studEarrings: { code: earsManStudEarrings },
  })
  .withComponents('eyes', {
    big: { code: eyesManBig },
    happy: { code: eyesManHappy },
    small: { code: eyesManSmall },
    standard: { code: eyesManStandard },
    eyelashes: { code: eyesManEyelashes },
    eyelids: { code: eyesManEyelids },
  })
  .withComponents('faceDetails', {
    chinDimple1: { code: faceDetailsChinDimple1 },
    chinDimple2: { code: faceDetailsChinDimple2 },
    chinDimple3: { code: faceDetailsChinDimple3 },
    chinDimple4: { code: faceDetailsChinDimple4 },
  })
  .withComponents('glasses', {
    brow: { code: glassesManBrow },
    patch: { code: glassesManPatch },
    round: { code: glassesManRound },
    square: { code: glassesManSquare },
    stylish: { code: glassesManStylish },
  })
  .withComponents('hair', {
    bald: { code: hairManBald },
    curly: { code: hairManCurly },
    elvis: { code: hairManElvis },
    mediumTopknot: { code: hairManMediumTopknot },
    messy: { code: hairManMessy },
    shortTopknot: { code: hairManShortTopknot },
    stylish: { code: hairManStylish },
    beanie: { code: hairBeanie },
  })
  .withComponents('head', {
    beardMustache: { code: headManBeardMustache },
    beardSharp: { code: headManBeardSharp },
    beardSlim: { code: headManBeardSlim },
    beardStandard: { code: headManBeardStandard },
    bristle: { code: headManBristle },
    bristleMustache: { code: headManBristleMustache },
    chin: { code: headManChin },
    sharp: { code: headManSharp },
    standard: { code: headManStandard },
  })
  .withComponents('mouth', {
    chin: { code: mouthChin },
    philtrum1: { code: mouthPhiltrum1 },
    philtrum2: { code: mouthPhiltrum2 },
    sad: { code: mouthSad },
    small: { code: mouthSmall },
    smile: { code: mouthSmile },
    tongue1: { code: mouthTongue1 },
    tongue2: { code: mouthTongue2 },
    vampire: { code: mouthVampire },
  })
  .withComponents('nose', {
    big: { code: noseManBig },
    bigWide: { code: noseManBigWide },
    small: { code: noseManSmall },
    standard: { code: noseManStandard },
    wide: { code: noseManWide },
  })
  .build()
